image: ${dockerHub}doctoolchain/doctoolchain:v2.2.1

pages:
  tags:
    - cdaas-shared-agent
  stage: build
  script:
    - export DTC_HEADLESS=true
    - ./dtcw generateSite --info
    - mkdir public
    - cp -r build/microsite/output/. public/.
  artifacts:
    paths:
      - public/
