image: ${dockerHub}doctoolchain/doctoolchain:v3.0.2

pages:
  tags:
    - $gitlabRunner
  stage: build
  script:
    - export DTC_HEADLESS=true
    - ./dtcw generateSite
    - mkdir public
    - cp -r build/microsite/output/. public/.
  artifacts:
    paths:
      - public/
