image: ${dockerHub}doctoolchain/doctoolchain:v3.2.2

pages:
  tags:
    - cdaas-shared-agent
  stage: build
  script:
    - export DTC_HEADLESS=true
    - export DTC_OPTS="-PmavenRepository=$artifactoryGradlePlugins -PdepsMavenRepository=$artifactoryMaven"
    - ./dtcw local generateSite --info --profile -I $(pwd)/init.gradle
    - mkdir public
    - cp -r build/microsite/output/. public/.
  artifacts:
    paths:
      - public/
