name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLES: true
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: chmod +x dtcw
      - name: generateSite
        run: ./dtcw generateSite
      - name: copyToPublic
        run: cp -r ./build/microsite/output ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847  # v3.9.3
        #        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public